### ISSUE TITLE
Create all products view

### ISSUE THREAD

**Issue by thingung** [team-thyme-fsa/grace-shopper#15]

**Comment by cxb0934** [comment]
TODO: change to functional component

**Comment by cxb0934** [comment]
TODO: add css to navbar

**Comment by cxb0934** [comment]
❓❓TODO: vote for navbar buttons❓❓

**Comment by cxb0934** [comment]
❓❓TODO: npm install for fontawesome dependencies❓❓

**Comment by cxb0934** [comment]
TODO: add css to product widget

**Comment by cxb0934** [comment]
❓❓TODO: vote for favicon❓❓
